/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import negocio.ProductoNegocio;
import javax.swing.JOptionPane;
import excepciones.DatoInvalidoException;

/**
 *
 * @author damur
 */
public class ListaProductosPanel extends javax.swing.JPanel {
    private ProductoNegocio negocio;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form ListaProductosPanel
     */
    public ListaProductosPanel(ProductoNegocio negocio){
        initComponents();
        
        this.negocio = negocio;

        modeloTabla = new DefaultTableModel();
        tblProductos.setModel(modeloTabla);

        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Categoría");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Precio");
        
        actualizarTabla();
    }
    
    public void actualizarTabla() {

        modeloTabla.setRowCount(0);

        for (Producto producto : negocio.getRepositorio().listar()) {

            modeloTabla.addRow(new Object[]{
                producto.getId(),
                producto.getCodigo(),
                producto.getNombre(),
                producto.getCategoria(),
                producto.getCantidad(),
                producto.getPrecio()
                    
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnOrdenarPrecio = new javax.swing.JButton();
        btnOrdenarCantidad = new javax.swing.JButton();

        lblBuscar.setText("Buscar");

        btnBuscar.setText("Buscar producto");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        scrollProductos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                scrollProductosComponentResized(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nombre", "Categoría", "Cantidad", "Precio", "Disponible"
            }
        ));
        scrollProductos.setViewportView(tblProductos);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(this::btnOrdenarActionPerformed);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Electrónica", "Alimentos", "Ropa", "Hogar", "Oficina", "Otros" }));
        cmbCategoria.addActionListener(this::cmbCategoriaActionPerformed);

        btnOrdenarPrecio.setText("Ordenar por Precio");
        btnOrdenarPrecio.addActionListener(this::btnOrdenarPrecioActionPerformed);

        btnOrdenarCantidad.setText("Ordenar por Cantidad");
        btnOrdenarCantidad.addActionListener(this::btnOrdenarCantidadActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(71, 71, 71)
                                .addComponent(btnOrdenar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnOrdenarPrecio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnOrdenarCantidad)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenarPrecio)
                    .addComponent(btnOrdenarCantidad))
                .addGap(33, 33, 33)
                .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnOrdenar)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scrollProductosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_scrollProductosComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_scrollProductosComponentResized

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dato = txtBuscar.getText().trim();

        Producto producto = negocio.buscarProducto(dato);

        if (producto == null) {
            producto = negocio.buscarPorNombre(dato);
        }

        modeloTabla.setRowCount(0);

        if (producto != null) {

            modeloTabla.addRow(new Object[]{
                producto.getId(),
                producto.getCodigo(),
                producto.getNombre(),
                producto.getCategoria(),
                producto.getCantidad(),
                producto.getPrecio(),
                producto.isDisponible()
            });

        } else {

            JOptionPane.showMessageDialog(this,
                "No se encontró el producto.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarTabla();
        txtBuscar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {

            String codigo = txtBuscar.getText();

            if (codigo.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Digite el código del producto a eliminar.");
                return;
            }

            int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este producto?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {

                negocio.eliminarProducto(codigo);

                JOptionPane.showMessageDialog(this,
                    "Producto eliminado correctamente.");

                actualizarTabla();
                txtBuscar.setText("");
            }

        }catch (DatoInvalidoException ex){

            JOptionPane.showMessageDialog(this,
                ex.getMessage());

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        negocio.ordenarProductos();

        actualizarTabla();

        JOptionPane.showMessageDialog(this,
            "Productos ordenados correctamente.");
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        String categoria = cmbCategoria.getSelectedItem().toString();

        modeloTabla.setRowCount(0);

        for (Producto producto : negocio.listarProductos()) {

            if (categoria.equals("Todas") ||
                producto.getCategoria().equalsIgnoreCase(categoria)) {

                modeloTabla.addRow(new Object[]{
                    producto.getId(),
                    producto.getCodigo(),
                    producto.getNombre(),
                    producto.getCategoria(),
                    producto.getCantidad(),
                    producto.getPrecio(),
                    producto.isDisponible()
                });
            }
        }
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnOrdenarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPrecioActionPerformed
        negocio.ordenarPorPrecio();

        actualizarTabla();

        JOptionPane.showMessageDialog(this,
            "Productos ordenados por precio.");
    }//GEN-LAST:event_btnOrdenarPrecioActionPerformed

    private void btnOrdenarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarCantidadActionPerformed
        negocio.ordenarPorCantidad();

        actualizarTabla();

        JOptionPane.showMessageDialog(this,
            "Productos ordenados por cantidad.");
    }//GEN-LAST:event_btnOrdenarCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnOrdenarCantidad;
    private javax.swing.JButton btnOrdenarPrecio;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JScrollPane scrollProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
